# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: settings.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Window functions

APP_CHOICE = 10000
ID_APPNAME = 10001
ID_TEXT = 10002
MODIFIER_LEFT = 10003
KEY_LEFT = 10004
MODIFIER_RIGHT = 10005
KEY_RIGHT = 10006
MODIFIER_POPEN = 10007
KEY_POPEN = 10008
MODIFIER_PCLOSE = 10009
KEY_PCLOSE = 10010
WORKS_ON = 10011
CONFIG_SAVE = 10012
APP_DELETE = 10013

def ApplicationConfig( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.BoxSizer( wx.VERTICAL )
    
    item3 = wx.BoxSizer( wx.HORIZONTAL )
    
    item4 = wx.Choice( parent, APP_CHOICE, wx.DefaultPosition, [150,-1], 
        ["ChoiceItem"] , 0 )
    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item5 = wx.StaticText( parent, ID_APPNAME, "configuration", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item5, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2.Add( item3, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item7 = wx.StaticText( parent, ID_TEXT, "On Hand/Face Move Left", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item7, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item8 = wx.ComboBox( parent, MODIFIER_LEFT, "", wx.DefaultPosition, [100,-1], 
        ["(nothing)","Alt","Ctrl","Shift"] , wx.CB_DROPDOWN|wx.CB_READONLY )
    item6.Add( item8, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item9 = wx.ComboBox( parent, KEY_LEFT, "", wx.DefaultPosition, [100,-1], 
        ["Left","Right","Up","Down"] , wx.CB_DROPDOWN|wx.CB_READONLY )
    item6.Add( item9, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item10 = wx.StaticText( parent, ID_TEXT, "On Hand/Face Move Right", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item10, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item11 = wx.ComboBox( parent, MODIFIER_RIGHT, "", wx.DefaultPosition, [100,-1], 
        ["(nothing)","Alt","Ctrl","Shift"] , wx.CB_DROPDOWN|wx.CB_READONLY )
    item6.Add( item11, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item12 = wx.ComboBox( parent, KEY_RIGHT, "", wx.DefaultPosition, [100,-1], 
        ["Left","Right","Up","Down"] , wx.CB_DROPDOWN|wx.CB_READONLY )
    item6.Add( item12, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item13 = wx.StaticText( parent, ID_TEXT, "On Palm Open/On Face Near", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item13, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item14 = wx.ComboBox( parent, MODIFIER_POPEN, "", wx.DefaultPosition, [100,-1], 
        ["(nothing)","Alt","Ctrl","Shift"] , wx.CB_DROPDOWN|wx.CB_READONLY )
    item6.Add( item14, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item15 = wx.ComboBox( parent, KEY_POPEN, "", wx.DefaultPosition, [100,-1], 
        ["Left","Right","Up","Down"] , wx.CB_DROPDOWN|wx.CB_READONLY )
    item6.Add( item15, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item16 = wx.StaticText( parent, ID_TEXT, "On Palm Close/On Face Far", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item16, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item17 = wx.ComboBox( parent, MODIFIER_PCLOSE, "", wx.DefaultPosition, [100,-1], 
        ["(nothing)","Alt","Ctrl","Shift"] , wx.CB_DROPDOWN|wx.CB_READONLY )
    item6.Add( item17, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item18 = wx.ComboBox( parent, KEY_PCLOSE, "", wx.DefaultPosition, [100,-1], 
        ["Left","Right","Up","Down"] , wx.CB_DROPDOWN|wx.CB_READONLY )
    item6.Add( item18, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item19 = wx.BoxSizer( wx.HORIZONTAL )
    
    item20 = wx.StaticText( parent, ID_TEXT, "Works with:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item19.Add( item20, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item21 = wx.ComboBox( parent, WORKS_ON, "", wx.DefaultPosition, [230,-1], 
        ["Face Detection and Tracking","Hand Gesture Recognition and Tracking","Both Face & Hand"] , wx.CB_DROPDOWN|wx.CB_READONLY )
    item19.Add( item21, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2.Add( item19, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item1.Add( item2, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item22 = wx.BoxSizer( wx.HORIZONTAL )
    
    item23 = wx.Button( parent, CONFIG_SAVE, "Save", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.Add( item23, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item24 = wx.Button( parent, APP_DELETE, "Delete", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.Add( item24, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item22, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_LINE = 10014
CHOICE_FACE = 10015
CHOICE_HAND = 10016
SAVE_METHOD = 10017

def MainDialog( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item0.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item1 = wx.StaticText( parent, ID_TEXT, "How do you want the tracking to be done?", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [200,-1], wx.LI_HORIZONTAL )
    item0.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3 = wx.BoxSizer( wx.VERTICAL )
    
    item4 = wx.RadioButton( parent, CHOICE_FACE, "Face Detection and Tracking", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item5 = wx.RadioButton( parent, CHOICE_HAND, "Hand Gesture Recognition and Tracking", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item5, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item6 = wx.Button( parent, SAVE_METHOD, "Save", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ADD_APP = 10018

def ApplicationList( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    parent.app_list_vsizer = item0
    
    item1 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticText( parent, ID_TEXT, "List of Applications:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item2, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [300,-1], wx.LI_HORIZONTAL )
    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item4 = wx.BoxSizer( wx.VERTICAL )
    parent.app_list = item4
    
    item1.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item5 = wx.Button( parent, ADD_APP, "Add a new application", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.SetDefault()
    item1.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

NEW_APP_NAME = 10019
ADD_APP_TO_LIST = 10020

def NewApplication( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Enter the new application name:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2 = wx.TextCtrl( parent, NEW_APP_NAME, "", wx.DefaultPosition, [200,-1], 0 )
    item0.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3 = wx.Button( parent, ADD_APP_TO_LIST, "Add", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_NOTEBOOK = 10021
EXIT_APP = 10022

def NotebookTab( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    parent.NOTEBOOK = item0
    
    item2 = wx.Notebook( parent, ID_NOTEBOOK, wx.DefaultPosition, [450,300], 0 )
    item1 = item2
    
    item3 = wx.Panel( item2, -1 )
    MainDialog(item3, False)
    item2.AddPage( item3, "Main Settings" )

    item4 = wx.Panel( item2, -1 )

    ApplicationList(item4, False)
    item2.AddPage( item4, "Application List" )

    item5 = wx.Panel( item2, -1 )
    ApplicationConfig(item5, False)
    item2.AddPage( item5, "Application Config" )

    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item6 = wx.BoxSizer( wx.HORIZONTAL )
    
    item7 = wx.Button( parent, EXIT_APP, "Hide", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item6, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

ID_MENU = 10023

def MyMenuBarFunc():
    item0 = wx.MenuBar()
    
    item1 = wx.Menu()
    item1.Append( wx.ID_ABOUT, "About", "" )
    item1.Append( wx.ID_EXIT, "Quit", "" )
    item0.Append( item1, "File" )
    
    return item0

# Toolbar functions


def MyToolBarFunc( parent ):
    parent.SetMargins( [2,2] )
    
    
    parent.Realize()

# Bitmap functions


# End of generated file
